export const FETCH_QUEUE_MESSAGES_REQUEST = 'FETCH_QUEUE_MESSAGES_REQUEST';
export const FETCH_QUEUE_MESSAGES_SUCCESS = 'FETCH_QUEUE_MESSAGES_SUCCESS';
export const FETCH_QUEUE_MESSAGES_FAILURE = 'FETCH_QUEUE_MESSAGES_FAILURE';

